name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build-type: [release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxi-dev \
            libxrandr-dev \
            libgl1-mesa-dev \
            libncurses5

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        if: runner.os != 'Windows' # Windows uses MSVC
        with:
          env: true
          version: 17

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.1

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "cd124b84feb0c02a24a2d90981e8358fdee0e077"

      - name: Determine CMake Preset
        id: select-preset
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            prefix="win"
          elif [ "${{ runner.os }}" == "Linux" ]; then
            prefix="linux"
          elif [ "${{ runner.os }}" == "macOS" ]; then
            prefix="mac"
          fi
          preset="${prefix}-${{ matrix.build-type }}"
          echo "preset=$preset" >> $GITHUB_OUTPUT
        shell: bash

      - name: Use Developer Command Prompt for Microsoft Visual C++
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake --preset ${{ steps.select-preset.outputs.preset }}
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Build
        run: cmake --build . --preset ${{ steps.select-preset.outputs.preset }} -v
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: Blur-${{ runner.os }}
          path: |
            ${{ runner.os == 'Windows' && 'bin/Release/blur-cli.exe' || 'bin/Release/blur-cli' }}
            ${{ runner.os == 'Windows' && 'bin/Release/blur.exe' || runner.os == 'macOS' && 'bin/Release/Blur' || 'bin/Release/blur' }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ env.is_tag == 'true' }}
        with:
          files: |
            ${{ runner.os == 'Windows' && 'bin/Release/blur-cli.exe' || 'bin/Release/blur-cli' }}
            ${{ runner.os == 'Windows' && 'bin/Release/blur.exe' || runner.os == 'macOS' && 'bin/Release/Blur' || 'bin/Release/blur' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
